"""empty message

Revision ID: 8a88ffb37be2
Revises: 
Create Date: 2018-09-19 11:29:22.346213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a88ffb37be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Remision', sa.Column('observaciones', sa.Text(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Remision', 'observaciones')
    # ### end Alembic commands ###
