"""empty message

Revision ID: e8228f4480ff
Revises: 
Create Date: 2017-09-02 22:52:54.100993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8228f4480ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ParametrosFactura',
    sa.Column('num_fac_ini', sa.Integer(), nullable=False),
    sa.Column('num_fac_fin', sa.Integer(), nullable=True),
    sa.Column('num_resolucion', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('num_fac_ini')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ParametrosFactura')
    # ### end Alembic commands ###
